name: 'Generate Job Openings'

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  execute_typescript:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./newPipeline

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Make the script files executable
        run: chmod +x refetchJobData.sh

      - name: Run Bash script
        run: ./refetchJobData.sh

      - name: Commit and Push changes
        run: |
          git config --global user.name 'long724'
          git config --global user.email 'justin.long596@gmail.com'
          git add -A
          git commit -m "Updating jobs data" -a || echo "No changes to commit"
          git push https://${{ secrets.GH_TOKEN }}@github.com/longj724/AI-Job-Board.git HEAD:main
