name: 'VC Backed Job'

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  execute_typescript:
    runs-on: ubuntu-latest
    defaults:
      working-directory: ./newPipeline

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '20' # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Make the script files executable
        run: chmod +x refetchJobData.sh

      - name: Run Bash script
        run: ./newPipeline/refetchJobData.sh

      - name: Commit and Push changes
        run: |
          git config --global user.name 'long724'
          git config --global user.email 'justin.long586@gmail.com'
          git add -A
          git commit -m "Fetching updated data" -a || echo "No changes to commit"
          git push
